name: build hello world
on:
  push:
    branches: [main, feature/workflow]

jobs:
  build:
     name: build
     runs-on: windows-latest
     
     steps:
       - name: Pull repo
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
       - name: Install msbuild
         uses: microsoft/setup-msbuild@v1.1

       - name: Build program
         id: build
         run: msbuild hello.c

    
